apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    run: {{ .Values.runTask }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: https
  selector:
    run: {{ .Release.Name }}-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: {{ .Release.Name }}-service # TODO: this needs to be changed i think
  template:
    metadata:
      labels:
        run: {{ .Release.Name }}-service # TODO: this needs to be changed i think
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.image.name }}
          name: {{ .Release.Name }}
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
