apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-service
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.name }}
          imagePullPolicy:  {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Release.Name }}-ep
              containerPort: {{ .Values.port }}
      restartPolicy: Always
