---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ .Release.Name }}-mapping
spec:
  grpc: True
  prefix: /{{ .Values.packageName }}.{{ .Values.serviceName }}
  rewrite: /{{ .Values.packageName }}.{{ .Values.serviceName }}
  service: {{ .Release.Name }}-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  ports:
    - name: {{ .Release.Name }}-p
      port: 80
      targetPort: {{ .Release.Name }}-ep
  selector:
    service: {{ .Release.Name }}-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-service
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.name }}
          imagePullPolicy:  {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Release.Name }}-ep
              containerPort: {{ .Values.port }}
      restartPolicy: Always
