apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: {{ .Values.runTask }}
  template:
    metadata:
      labels:
        run: {{ .Values.runTask }}
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.image.name }}
          name: {{ .Release.Name }}
          imagePullPolicy: Never
          resources: {}
          ports:
            - name: {{ .Release.Name }}-p
              containerPort: {{ .Values.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
