apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  ports:
    - name: {{ .Release.Name }}-p
      port: 80
      targetPort: {{ .Release.Name }}-ep
  selector:
    service: {{ .Release.Name }}-service
