apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-example
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: grpc-example
  template:
    metadata:
      labels:
        service: grpc-example
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.image.name }}
          name: grpc-example
          imagePullPolicy:  {{ .Values.image.pullPolicy }}
          resources: {}
          ports:
            - name: {{ .Release.Name }}-p
              containerPort: {{ .Values.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
