# TODO: maybe this should be in ambassador repo
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ .Release.Name }}-grpc-mapping
  namespace: default # TODO: change this to get from .values
spec:
  grpc: true
  prefix: /app.AppController/
  rewrite: /app.AppController/
  service: grpc-example
